# Generated by Django 3.2.6 on 2021-08-09 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bingo_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='moveuser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='move_user', to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='update',
            field=models.BooleanField(default=False),
        ),
    ]
