# Generated by Django 3.2.6 on 2021-08-10 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bingo_game', '0002_auto_20210809_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='board',
        ),
        migrations.RemoveField(
            model_name='game',
            name='moveuser',
        ),
        migrations.RemoveField(
            model_name='game',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='game',
            name='user2',
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=100)),
                ('is_my_move', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(to='bingo_game.Player'),
        ),
    ]
